#!/usr/bin/env bash
# creates a PID file and displays specific text

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
  touch "$file"
fi

sleep 2 &

echo "$!" > "$file"

# now we print a text, delete the file and exit after the signal. 
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# print more text after SIGINT signal
trap "echo Y U no love me?!" SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
