#!/usr/bin/env bash
# script using if and while to displays ‘Best School’ 10 times
# prints ‘hi’ at the 9th

a=1

while [ $a -le 10 ]
do
    echo "Best School"
    if [ $a -eq 9 ]
    then
        echo "Hi"
    fi
    ((a++))
done
